// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExtractTranslations(arg1:string,arg2:string):Promise<main.BatchResult>;

export function ExtractTranslationsBatch(arg1:string,arg2:string):Promise<main.BatchResult>;

export function GetLCSEPath():Promise<string>;

export function GetOneHookConfig():Promise<Record<string, string>>;

export function GetToolPaths():Promise<Record<string, string>>;

export function InstallOneHook(arg1:string,arg2:string,arg3:string):Promise<string>;

export function MoonAssembleScripts(arg1:string,arg2:string):Promise<string>;

export function MoonBundledScriptsToUTF(arg1:string):Promise<main.BatchResult>;

export function MoonConvertImages(arg1:string,arg2:string):Promise<main.BatchResult>;

export function MoonExportDialogues(arg1:string,arg2:string):Promise<main.BatchResult>;

export function MoonExtractImagesFromArchive(arg1:string,arg2:string):Promise<main.BatchResult>;

export function MoonImportDialogues(arg1:string,arg2:string,arg3:string):Promise<main.BatchResult>;

export function MoonSNXToTXT(arg1:string,arg2:string):Promise<string>;

export function MoonScriptsToUTF(arg1:string,arg2:string):Promise<main.BatchResult>;

export function MoonTXTToSNX(arg1:string,arg2:string):Promise<string>;

export function MoonUnpackArchive(arg1:string,arg2:string):Promise<string>;

export function OneExportDialogues(arg1:string,arg2:string):Promise<main.BatchResult>;

export function OneImportDialogues(arg1:string,arg2:string,arg3:string):Promise<main.BatchResult>;

export function PackArchive(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function PatchArchive(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<string>;

export function ReinjectTranslations(arg1:string,arg2:string,arg3:string):Promise<main.BatchResult>;

export function ReinjectTranslationsBatch(arg1:string,arg2:string,arg3:string):Promise<main.BatchResult>;

export function SNXToTXT(arg1:string,arg2:string):Promise<string>;

export function SaveOneHookConfig(arg1:string,arg2:string):Promise<string>;

export function SelectAnyFile(arg1:string):Promise<string>;

export function SelectArchiveBase():Promise<string>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SelectSNXFile():Promise<string>;

export function SelectSaveFile(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function SelectTSVFile():Promise<string>;

export function SelectTXTFile():Promise<string>;

export function SetLCSEPath():Promise<string>;

export function StopProcess():Promise<void>;

export function TXTToSNX(arg1:string,arg2:string,arg3:string):Promise<string>;

export function TXTToSNXBatch(arg1:string,arg2:string,arg3:string):Promise<string>;

export function UnpackArchive(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;
