// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExtractTranslations(arg1, arg2) {
  return window['go']['main']['App']['ExtractTranslations'](arg1, arg2);
}

export function ExtractTranslationsBatch(arg1, arg2) {
  return window['go']['main']['App']['ExtractTranslationsBatch'](arg1, arg2);
}

export function GetLCSEPath() {
  return window['go']['main']['App']['GetLCSEPath']();
}

export function GetOneHookConfig() {
  return window['go']['main']['App']['GetOneHookConfig']();
}

export function GetToolPaths() {
  return window['go']['main']['App']['GetToolPaths']();
}

export function InstallOneHook(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallOneHook'](arg1, arg2, arg3);
}

export function MoonAssembleScripts(arg1, arg2) {
  return window['go']['main']['App']['MoonAssembleScripts'](arg1, arg2);
}

export function MoonBundledScriptsToUTF(arg1) {
  return window['go']['main']['App']['MoonBundledScriptsToUTF'](arg1);
}

export function MoonConvertImages(arg1, arg2) {
  return window['go']['main']['App']['MoonConvertImages'](arg1, arg2);
}

export function MoonExportDialogues(arg1, arg2) {
  return window['go']['main']['App']['MoonExportDialogues'](arg1, arg2);
}

export function MoonExtractImagesFromArchive(arg1, arg2) {
  return window['go']['main']['App']['MoonExtractImagesFromArchive'](arg1, arg2);
}

export function MoonImportDialogues(arg1, arg2, arg3) {
  return window['go']['main']['App']['MoonImportDialogues'](arg1, arg2, arg3);
}

export function MoonSNXToTXT(arg1, arg2) {
  return window['go']['main']['App']['MoonSNXToTXT'](arg1, arg2);
}

export function MoonScriptsToUTF(arg1, arg2) {
  return window['go']['main']['App']['MoonScriptsToUTF'](arg1, arg2);
}

export function MoonTXTToSNX(arg1, arg2) {
  return window['go']['main']['App']['MoonTXTToSNX'](arg1, arg2);
}

export function MoonUnpackArchive(arg1, arg2) {
  return window['go']['main']['App']['MoonUnpackArchive'](arg1, arg2);
}

export function OneExportDialogues(arg1, arg2) {
  return window['go']['main']['App']['OneExportDialogues'](arg1, arg2);
}

export function OneImportDialogues(arg1, arg2, arg3) {
  return window['go']['main']['App']['OneImportDialogues'](arg1, arg2, arg3);
}

export function PackArchive(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PackArchive'](arg1, arg2, arg3, arg4);
}

export function PatchArchive(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PatchArchive'](arg1, arg2, arg3, arg4, arg5);
}

export function ReinjectTranslations(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReinjectTranslations'](arg1, arg2, arg3);
}

export function ReinjectTranslationsBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['ReinjectTranslationsBatch'](arg1, arg2, arg3);
}

export function SNXToTXT(arg1, arg2) {
  return window['go']['main']['App']['SNXToTXT'](arg1, arg2);
}

export function SaveOneHookConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveOneHookConfig'](arg1, arg2);
}

export function SelectAnyFile(arg1) {
  return window['go']['main']['App']['SelectAnyFile'](arg1);
}

export function SelectArchiveBase() {
  return window['go']['main']['App']['SelectArchiveBase']();
}

export function SelectDirectory(arg1) {
  return window['go']['main']['App']['SelectDirectory'](arg1);
}

export function SelectSNXFile() {
  return window['go']['main']['App']['SelectSNXFile']();
}

export function SelectSaveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SelectSaveFile'](arg1, arg2, arg3, arg4);
}

export function SelectTSVFile() {
  return window['go']['main']['App']['SelectTSVFile']();
}

export function SelectTXTFile() {
  return window['go']['main']['App']['SelectTXTFile']();
}

export function SetLCSEPath() {
  return window['go']['main']['App']['SetLCSEPath']();
}

export function StopProcess() {
  return window['go']['main']['App']['StopProcess']();
}

export function TXTToSNX(arg1, arg2, arg3) {
  return window['go']['main']['App']['TXTToSNX'](arg1, arg2, arg3);
}

export function TXTToSNXBatch(arg1, arg2, arg3) {
  return window['go']['main']['App']['TXTToSNXBatch'](arg1, arg2, arg3);
}

export function UnpackArchive(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UnpackArchive'](arg1, arg2, arg3, arg4);
}
